services:
  - type: web
    name: desk-butler-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PROXY_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    runtime: python3.11
